### ISSUE TITLE
Add support for `${{ github.environment.url }}`

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/action-wordpress-plugin-release#2]
Current config is not completely DRY, users have to config the environment URL and the WordPress.org plugin slug:

```
    environment:
      name: WordPress.org plugin directory
      url: https://wordpress.org/plugins/salesfeed/ 👈
```

```
        with:
          username: ${{ vars.WORDPRESS_ORG_PRONAMIC_USERNAME }}
          password: ${{ secrets.WORDPRESS_ORG_PRONAMIC_PASSWORD }}
          tag: ${{ inputs.tag || github.event.release.tag_name }}
          slug: salesfeed 👈
```

https://github.com/pronamic/wp-salesfeed/blob/4f51e5d34fc81f931b2ff80b34717766a370ce14/.github/workflows/deploy-to-wordpress-org.yml#L1-L30

Maybe we can add support for `${{ github.environment.url }}`?

```
        with:
          username: ${{ vars.WORDPRESS_ORG_PRONAMIC_USERNAME }}
          password: ${{ secrets.WORDPRESS_ORG_PRONAMIC_PASSWORD }}
          tag: ${{ inputs.tag || github.event.release.tag_name }}
          url: ${{ github.environment.url }}
```

We can retrieve the slug from the https://wordpress.org/plugins/salesfeed/ URL.
